// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-activities.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/data.ts
var DATA_URL = "https://familyfun.pl/data/activities.json";
var cache = null;
var TTL_MS = 5 * 60 * 1e3;
async function fetchActivities() {
  if (cache && Date.now() - cache.at < TTL_MS) return cache.data;
  const res = await fetch(DATA_URL, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`Failed to load activities: ${res.status}`);
  const data = await res.json();
  cache = { at: Date.now(), data };
  return data;
}

// src/lib/mcp/tools/search-activities.ts
var search_activities_default = defineTool({
  name: "search_activities",
  title: "Search FamilyFun activities",
  description: "Search family activities from the FamilyFun catalog (5 Polish cities). Filter by city, category/tag, indoor/outdoor, or a free-text query matched against title, location, tags and description.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text query matched against title, location, tags, description."),
    city: z.enum(["warszawa", "krakow", "wroclaw", "poznan", "gdansk"]).optional().describe("City slug filter."),
    indoor: z.boolean().optional().describe("If true, only indoor. If false, only outdoor."),
    tag: z.string().trim().optional().describe("Tag/category filter (case-insensitive contains)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results, default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, indoor, tag, limit }) => {
    const all = await fetchActivities();
    const q = query?.toLowerCase();
    const t = tag?.toLowerCase();
    const filtered = all.filter((a) => {
      if (city && a.city !== city) return false;
      if (indoor !== void 0 && a.isIndoor !== indoor) return false;
      if (t && !(a.tags || []).some((x) => x.toLowerCase().includes(t))) return false;
      if (q) {
        const hay = [a.title, a.location, a.description ?? "", (a.tags || []).join(" ")].join(" ").toLowerCase();
        if (!hay.includes(q)) return false;
      }
      return true;
    });
    const results = filtered.sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0)).slice(0, limit ?? 10).map((a) => ({
      id: a.id,
      slug: a.slug,
      title: a.title,
      city: a.city,
      location: a.location,
      rating: a.rating,
      reviewCount: a.reviewCount,
      ageRange: a.ageRange,
      isIndoor: a.isIndoor,
      tags: a.tags,
      url: `https://familyfun.pl/atrakcje/${a.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ count: results.length, results }, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/get-activity.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
var get_activity_default = defineTool2({
  name: "get_activity",
  title: "Get FamilyFun activity details",
  description: "Fetch full details for one FamilyFun activity by its slug (e.g. 'warszawa-zoo-warszawskie').",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Activity slug, e.g. 'warszawa-zoo-warszawskie'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const all = await fetchActivities();
    const a = all.find((x) => x.slug === slug);
    if (!a) {
      return {
        content: [{ type: "text", text: `No activity found with slug '${slug}'.` }],
        isError: true
      };
    }
    const detail = {
      id: a.id,
      slug: a.slug,
      title: a.title,
      city: a.city,
      location: a.location,
      address: a.address,
      rating: a.rating,
      reviewCount: a.reviewCount,
      ageRange: a.ageRange,
      isIndoor: a.isIndoor,
      tags: a.tags,
      description: a.description,
      openingHours: a.openingHours,
      priceRange: a.priceRange,
      priceLevel: a.priceLevel,
      website: a.website,
      latitude: a.latitude,
      longitude: a.longitude,
      url: `https://familyfun.pl/atrakcje/${a.slug}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(detail, null, 2) }],
      structuredContent: detail
    };
  }
});

// src/lib/mcp/tools/list-cities.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_cities_default = defineTool3({
  name: "list_cities",
  title: "List FamilyFun cities",
  description: "List Polish cities covered by FamilyFun with activity counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const all = await fetchActivities();
    const counts = {};
    for (const a of all) counts[a.city] = (counts[a.city] ?? 0) + 1;
    const cities = Object.entries(counts).map(([slug, count]) => ({ slug, count })).sort((a, b) => b.count - a.count);
    return {
      content: [{ type: "text", text: JSON.stringify({ cities }, null, 2) }],
      structuredContent: { cities }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "familyfun-mcp",
  title: "FamilyFun MCP",
  version: "0.1.0",
  instructions: "Tools for FamilyFun (familyfun.pl), a catalog of family-friendly activities in 5 Polish cities (Warszawa, Krak\xF3w, Wroc\u0142aw, Pozna\u0144, Gda\u0144sk). Use `list_cities` to see coverage, `search_activities` to find places by city/tag/query, and `get_activity` to fetch details for a specific slug.",
  tools: [search_activities_default, get_activity_default, list_cities_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
