// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-activities.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/data.ts
var CATALOG_URL = "https://zpqpgatnnbojgiejmtpt.supabase.co";
var CATALOG_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwcXBnYXRubmJvamdpZWptdHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2MTY2OTIsImV4cCI6MjA5MzE5MjY5Mn0.nHm-KdlT1r2VlXQRfXqRDCCisU4KEf9yPI96kIpx4tc";
var SELECT = "slug,name,type,region,city,address,rating,reviews_count,description,price_note,website,opening_hours,image_url,lat,lng";
var cache = null;
var TTL_MS = 5 * 60 * 1e3;
async function fetchActivities() {
  if (cache && Date.now() - cache.at < TTL_MS) return cache.data;
  const url = `${CATALOG_URL}/rest/v1/public_activities?select=${encodeURIComponent(SELECT)}&published=eq.true&order=rating.desc.nullslast&limit=2000`;
  const res = await fetch(url, {
    headers: {
      accept: "application/json",
      apikey: CATALOG_ANON_KEY,
      authorization: `Bearer ${CATALOG_ANON_KEY}`
    }
  });
  if (!res.ok) throw new Error(`Failed to load activities: ${res.status}`);
  const rows = await res.json();
  const data = rows.map((r, i) => ({
    id: i + 1,
    slug: String(r.slug ?? ""),
    title: String(r.name ?? ""),
    location: String(r.city ?? r.region ?? ""),
    city: String(r.region ?? r.city ?? ""),
    rating: Number(r.rating ?? 0),
    reviewCount: Number(r.reviews_count ?? 0),
    ageRange: "",
    isIndoor: false,
    tags: [String(r.type ?? "")].filter(Boolean),
    description: r.description ?? void 0,
    address: r.address ?? void 0,
    website: r.website ?? void 0,
    latitude: Number(r.lat ?? 0),
    longitude: Number(r.lng ?? 0),
    openingHours: r.opening_hours ?? void 0,
    priceRange: r.price_note ?? void 0,
    imageUrl: r.image_url ?? void 0
  }));
  cache = { at: Date.now(), data };
  return data;
}

// src/lib/mcp/tools/search-activities.ts
var search_activities_default = defineTool({
  name: "search_activities",
  title: "Search FamilyFun activities",
  description: "Search family activities from the FamilyFun catalog (Poland \u2014 mainly the Warsaw and Silesia regions). Filter by city/region, category/tag, indoor/outdoor, or a free-text query matched against title, location, tags and description.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text query matched against title, location, tags, description."),
    city: z.enum(["warszawa", "slask"]).optional().describe(
      "Region slug filter: 'warszawa' (Warsaw area) or 'slask' (Silesian agglomeration). Smaller towns appear under their own city values \u2014 use `list_cities` for full coverage and the free-text query to match them."
    ),
    indoor: z.boolean().optional().describe("If true, only indoor. If false, only outdoor."),
    tag: z.string().trim().optional().describe("Tag/category filter (case-insensitive contains)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results, default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, indoor, tag, limit }) => {
    const all = await fetchActivities();
    const q = query?.toLowerCase();
    const t = tag?.toLowerCase();
    const filtered = all.filter((a) => {
      if (city && a.city !== city) return false;
      if (indoor !== void 0 && a.isIndoor !== indoor) return false;
      if (t && !(a.tags || []).some((x) => x.toLowerCase().includes(t))) return false;
      if (q) {
        const hay = [a.title, a.location, a.description ?? "", (a.tags || []).join(" ")].join(" ").toLowerCase();
        if (!hay.includes(q)) return false;
      }
      return true;
    });
    const results = filtered.sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0)).slice(0, limit ?? 10).map((a) => ({
      id: a.id,
      slug: a.slug,
      title: a.title,
      city: a.city,
      location: a.location,
      rating: a.rating,
      reviewCount: a.reviewCount,
      ageRange: a.ageRange,
      isIndoor: a.isIndoor,
      tags: a.tags,
      url: `https://familyfun.pl/atrakcje/${a.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ count: results.length, results }, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/get-activity.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
var get_activity_default = defineTool2({
  name: "get_activity",
  title: "Get FamilyFun activity details",
  description: "Fetch full details for one FamilyFun activity by its slug (e.g. 'warszawa-zoo-warszawskie').",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Activity slug, e.g. 'warszawa-zoo-warszawskie'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const all = await fetchActivities();
    const a = all.find((x) => x.slug === slug);
    if (!a) {
      return {
        content: [{ type: "text", text: `No activity found with slug '${slug}'.` }],
        isError: true
      };
    }
    const detail = {
      id: a.id,
      slug: a.slug,
      title: a.title,
      city: a.city,
      location: a.location,
      address: a.address,
      rating: a.rating,
      reviewCount: a.reviewCount,
      ageRange: a.ageRange,
      isIndoor: a.isIndoor,
      tags: a.tags,
      description: a.description,
      openingHours: a.openingHours,
      priceRange: a.priceRange,
      priceLevel: a.priceLevel,
      website: a.website,
      latitude: a.latitude,
      longitude: a.longitude,
      url: `https://familyfun.pl/atrakcje/${a.slug}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(detail, null, 2) }],
      structuredContent: detail
    };
  }
});

// src/lib/mcp/tools/list-cities.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_cities_default = defineTool3({
  name: "list_cities",
  title: "List FamilyFun cities",
  description: "List Polish cities covered by FamilyFun with activity counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const all = await fetchActivities();
    const counts = {};
    for (const a of all) counts[a.city] = (counts[a.city] ?? 0) + 1;
    const cities = Object.entries(counts).map(([slug, count]) => ({ slug, count })).sort((a, b) => b.count - a.count);
    return {
      content: [{ type: "text", text: JSON.stringify({ cities }, null, 2) }],
      structuredContent: { cities }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "familyfun-mcp",
  title: "FamilyFun MCP",
  version: "0.1.0",
  instructions: "Tools for FamilyFun (familyfun.pl), a catalog of ~460 family-friendly activities in Poland \u2014 mainly the Warsaw area (city slug `warszawa`) and the Silesian agglomeration (`slask`), plus smaller nearby towns. Use `list_cities` to see coverage, `search_activities` to find places by city/tag/query, and `get_activity` to fetch details for a specific slug.",
  tools: [search_activities_default, get_activity_default, list_cities_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
